version: '3.8'
services:

  stream-video-app:
    image: stream-video-app
    container_name: stream-video-app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/workspace/server
      - /workspace/server/node_modules
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=testowa
      - MONGO_INITDB_ROOT_USERNAME=DefCodeMM
      - MONGO_INITDB_ROOT_PASSWORD=DefCodeMM
    ports:
      - '27017-27019:27017-27019'
    volumes: 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-data:/data/db
    restart: always

# networks:
#     nestjs-network: