version: '3.8'
services:

  stream-video-app:
    image: stream-video-app
    container_name: stream-video-app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/workspace/server
      - /workspace/server/node_modules
    networks:
      - stream-video-app-network
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    env_file: 
    - .env
    ports:
      - '27017-27019:27017-27019'
    volumes: 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-data:/data/db
    networks:
      - stream-video-app-network
    restart: always

  mongo-express:
    image: mongo-express
    container_name: mongo-web-admin
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGO_HOST}
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGO_DATABASE_NAME}
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    env_file: 
      - .env
    networks:
      - stream-video-app-network
    depends_on:
      - mongodb

networks:
    stream-video-app-network:
      driver: bridge
      name: stream-video-app-network