version: '3.7'

services:
  stream-video-app:
    image: stream-video-app
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/workspace/server
      - /workspace/server/node_modules
    restart: unless-stopped