version: '3.7'

services:
  stream-video-app:
    image: stream-video-app
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:dev
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - nestjs-network
    volumes:
      - .:/workspace/server
      - /workspace/server/node_modules
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
    volumes: 
        - ./mongo-data:/data/db

networks:
    nestjs-network: