name: Unit Tests

on: [push, pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 17.x]
        
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run start:dev
      # mocks need to be created, for now test only specific file
      - run: npm test